version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  setup:
    executor:
      name: node/default
    steps:
      - node/install:
          install-yarn: true
          node-version: latest
      - run:
          name: Downloading AWS cli
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; unzip awscliv2.zip
      - run:
          name: Installing AWS cli
          command: sudo ./aws/install; /usr/local/bin/aws --version
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Installing app dependencies
          command: yarn install
      - run:
          name: Building dist
          command: yarn build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist/*
  deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls -l /tmp/workspace/dist
      - run: ls -l
      - run:
          name: Deploying to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              /usr/local/bin/aws s3 sync ./dist s3://react-webgl-game --delete
            else
              echo "Not master branch, dry run only"
            fi
workflows:
    pipeline:
      jobs:
        - setup
        - build-and-deploy:
            requires:
              - setup
