version: 2.1
orbs:
  node: circleci/node@2.0.1
  s3: circleci/aws-s3@1.0.15
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Installing app dependencies
          command: yarn install
      - run:
          name: Building dist
          command: yarn build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist/*
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls -l /tmp/workspace/dist
      - run: ls -l
      - s3/sync:
          from: dist
          overwrite: true
          to: 's3://react-webgl-game'
workflows:
    pipeline:
      jobs:
        - build
        - deploy:
            requires:
              - build
