version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - yarn install
      - yarn build

workflows:
    pipeline:
      jobs:
        - build
