version: 2.1
orbs:
  node: circleci/node@2.0.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: yarn install
      - run: yarn build

workflows:
    pipeline:
      jobs:
        - build
